
// export {
//   surName,
//   middleName,
//   emailInput,
//   generatId,
//   password,
//   passwordConfirmation,
//   registerButton,
//   singIn,
//   validRegex,
//   targetSur,
//   targetMidName,
//   targetNotMatch,
//   targetiD,
//   targetidError,
//   targetPsw,
//   targetLessPsw,
//   targetPswConfirm,
//   targetPswdLess,
//   targetPswError,
// }
